version: "3.8"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_ORIGINS=http://localhost:3000
      - REDIS_URL=redis://redis:6379/0
      - USE_S3=true
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
    depends_on:
      - redis
      - minio
  
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: rq worker --url redis://redis:6379/0
    volumes:
      - ./backend/app:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - USE_S3=true
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
    depends_on:
      - redis
      - minio

volumes:
  redis_data:
  minio_data:
